//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibrary.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Movement = new HashSet<Movement>();
            this.Penalty = new HashSet<Penalty>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage ="Adý alanýný boþ býrakamazsýnýz!")]
        [StringLength(20,ErrorMessage ="Ad alanýna 20 karakter'den fazla girilemez.")]
        public string Name { get; set; }
        public string LastName { get; set; }
        //mail format
        public string Mail { get; set; }
        public string UserName { get; set; }
        [StringLength(20, ErrorMessage ="20 karakter'den büyük þifre girilemez.")]
        public string Password { get; set; }
        public string Photo { get; set; }
        public string Phone { get; set; }
        public string School { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movement> Movement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Penalty> Penalty { get; set; }
    }
}
